version: "3.7"

services:
  app:
    build: .
    command: npm run dev
    environment:
      - FAUCET_API=http://localhost:8080
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
